# Generated by Django 5.2.3 on 2025-07-30 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saiki_site', '0005_session_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model_Algorithm',
        ),
    ]
