# Generated by Django 5.2.4 on 2025-07-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saiki_site', '0005_session_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('data', models.JSONField()),
            ],
        ),
    ]
