# Generated by Django 5.2.3 on 2025-08-20 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saiki_site', '0006_delete_model_algorithm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('players', models.ManyToManyField(related_name='games', to='saiki_site.jogador')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='saiki_site.session')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='Jogo_custom',
            fields=[
                ('jogo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='saiki_site.jogo')),
            ],
            options={
                'verbose_name': 'Custom Game',
                'verbose_name_plural': 'Custom Games',
            },
            bases=('saiki_site.jogo',),
        ),
        migrations.CreateModel(
            name='Jogo_daily',
            fields=[
                ('jogo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='saiki_site.jogo')),
                ('daily_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Game',
                'verbose_name_plural': 'Daily Games',
            },
            bases=('saiki_site.jogo',),
        ),
    ]
