# Generated by Django 5.2.3 on 2025-08-20 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saiki_site', '0007_jogo_jogo_custom_jogo_daily'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo_VF',
            fields=[
                ('jogo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='saiki_site.jogo')),
                ('pontuacao', models.IntegerField(default=0)),
                ('acertos', models.IntegerField(default=0)),
                ('erros', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'VF Game',
                'verbose_name_plural': 'VF Games',
            },
            bases=('saiki_site.jogo',),
        ),
        migrations.AddField(
            model_name='jogo',
            name='tentativas',
            field=models.IntegerField(default=0),
        ),
    ]
