# Generated by Django 5.2.3 on 2025-07-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('year', models.IntegerField()),
                ('category', models.CharField(max_length=32)),
                ('design_paradigm', models.CharField(max_length=32)),
                ('generality', models.CharField(max_length=32)),
                ('data_structure', models.CharField(max_length=32)),
                ('temporal_complexity', models.CharField(max_length=32)),
                ('spatial_complexity', models.CharField(max_length=32)),
                ('solution_type', models.CharField(max_length=32)),
            ],
        ),
    ]
